/* Frozen initial artifacts, original videos, one run per ID plus S36 fixture control.
 * No scenario-name-derived ground truth. Review labels separately before scoring. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn,execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),frozen=path.join(root,'runs/surface-search/baseline-EQYvBO');
const ffmpeg='C:/dev/ffmpeg-master-latest-win64-gpl-shared/bin/ffmpeg.exe';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2));
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const out=process.argv[3]?path.resolve(process.argv[3]):fs.mkdtempSync(path.join(root,'runs/all50-initial-'));
function prepare(){
 const latest=new Map();for(const name of fs.readdirSync(path.join(root,'records')).sort()){
  const dir=path.join(root,'records',name);if(!fs.existsSync(path.join(dir,'session.json')))continue;
  for(const r of read(path.join(dir,'session.json')).results)if(r.status==='completed'&&r.filename){const video=path.join(dir,r.filename);if(path.basename(r.filename)!==r.filename||fs.statSync(video).size!==r.bytes_written)throw Error('Invalid video '+video);latest.set(r.scenario.id,{...r,video,session:name});}
 }
 const ids=Array.from({length:50},(_,i)=>'S'+String(i+1).padStart(2,'0'));if(ids.some(id=>!latest.has(id)))throw Error('Missing completed scenario');
 const config=read(path.join(frozen,'initial-evaluation/config.json'));write(path.join(out,'config.json'),config);
 const fixture=structuredClone(config);fixture.surfaces[0].fixtures=read(path.join(root,'config/video-evaluation/S36-fixture.json')).surfaces[0].fixtures;write(path.join(out,'S36-fixture-config.json'),fixture);
 const oldLabels=read(path.join(root,'runs/video-evaluation-3yhvPj/results.json'));
 const cases=ids.map(id=>{const r=latest.get(id),obs=r.prompts.find(p=>p.kind==='observe');if(!Number.isFinite(obs?.countdown_started_elapsed_s))throw Error('Missing observe timestamp '+id);const target=obs.countdown_started_elapsed_s+75;if(target>=r.observed_duration_s)throw Error('Reference outside video');const old=r.session.includes('2026-09-11')?oldLabels.find(x=>x.id===id):null;return {id,video:r.video,session:r.session,sha256:hash(r.video),reference_s:old?.reference_s??target,baseline_reference_s:r.prompts[0].countdown_started_elapsed_s+8,end_reference_s:r.observed_duration_s-3,observed_duration_s:r.observed_duration_s,expected_protocol:r.scenario.expected,expected_alert:old?old.expected_residue:null,label_basis:old?'previous manual checkpoint review':'pending manual review',protocol_note:id==='S33'?'Cup present from start; not clean-baseline then placement. Original unedited diagnostic run.':id==='S36'||id==='S37'?'Fixture scenario; initial unregistered config is primary control.':id==='S38'?'Fixture adjacency claim not yet verified; binary residue only.':id==='S39'?'Occupied-use policy: expected alert differs from physical cup presence.':''};});
 const exe=path.join(frozen,'evaluator/evaluate_surface_video.exe'),models=['yolo11n-pose-416x224.onnx','yolo11n_tier2_fp32.onnx'].map(x=>path.join(frozen,'models',x));
 write(path.join(out,'manifest.json'),{created_at:new Date().toISOString(),scope:'50 original-video late-observation checkpoints; not full-event accuracy or independent test',initial_config_sha256:hash(path.join(out,'config.json')),exe,models,artifacts:[exe,...models,path.join(frozen,'evaluator/onnxruntime.dll')].map(file=>({file,sha256:hash(file)})),sampling_hz:2,baseline_capture_video_s:15,between_videos_ms:10000,cases});
 write(path.join(out,'labels.json'),cases.map(c=>({id:c.id,expected_alert:c.expected_alert,basis:c.label_basis,protocol_note:c.protocol_note})));
 console.log('Prepared: '+out);
}
function stills(){const m=read(path.join(out,'manifest.json'));const dir=path.join(out,'review');fs.mkdirSync(dir,{recursive:true});for(const c of m.cases.filter(c=>c.session.includes('2026-09-14'))){for(const [label,t]of [['baseline',c.baseline_reference_s],['reference',c.reference_s],['end',c.end_reference_s]]){const dest=path.join(dir,c.id+'-'+label+'.jpg');if(fs.existsSync(dest))continue;execFileSync(ffmpeg,['-v','error','-threads','1','-ss',String(t),'-i',c.video,'-frames:v','1','-vf','crop=750:380:160:335,scale=600:304','-q:v','2',dest],{windowsHide:true,timeout:30000});}console.log('Review '+c.id);}}
async function run(){const m=read(path.join(out,'manifest.json'));for(const a of m.artifacts)if(hash(a.file)!==a.sha256)throw Error('Artifact changed');const jobs=[...m.cases,m.cases.find(c=>c.id==='S36')];for(let i=0;i<jobs.length;i++){
 const c=jobs[i],name=i===50?'S36-fixture':c.id,work=path.join(out,name);if(fs.existsSync(path.join(work,'result.json')))continue;if(fs.existsSync(work))throw Error('Incomplete directory: inspect before retry '+work);if(hash(c.video)!==c.sha256)throw Error('Video changed');fs.mkdirSync(work);
 write(path.join(out,'progress.json'),{state:'running',completed:i,total:51,current:name,at:new Date().toISOString()});
 const config=path.join(out,i===50?'S36-fixture-config.json':'config.json'),output=fs.createWriteStream(path.join(work,'predictions.jsonl')),errors=fs.createWriteStream(path.join(work,'process.log'));
 const ff=spawn(ffmpeg,['-v','error','-threads','1','-i',c.video,'-an','-vf','fps=fps=2:start_time=0','-pix_fmt','rgb24','-f','rawvideo','pipe:1'],{windowsHide:true,stdio:['ignore','pipe','pipe']}),p=spawn(m.exe,[config,work,...m.models,'1'],{windowsHide:true,stdio:['pipe','pipe','pipe']});
 const wait=child=>new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});const done=Promise.all([wait(ff),wait(p)]),closed=new Promise((resolve,reject)=>{output.on('close',resolve);output.on('error',reject);});ff.stdout.pipe(p.stdin);p.stdout.pipe(output);let logs='';p.stderr.on('data',b=>logs+=b);p.stderr.pipe(errors,{end:false});ff.stderr.pipe(errors,{end:false});p.stdin.on('error',()=>ff.kill());p.on('close',code=>{if(code)ff.kill();});const timeout=setTimeout(()=>{ff.kill();p.kill();},600000);
 try{const codes=await done;await closed;if(codes.some(x=>x!==0))throw Error('Subprocess failure '+codes); }finally{clearTimeout(timeout);ff.kill();p.kill();errors.end();}
 const seq=fs.readFileSync(path.join(work,'predictions.jsonl'),'utf8').trim().split('\n').map(JSON.parse),selected=seq.reduce((a,b)=>Math.abs(a.video_s-c.reference_s)<=Math.abs(b.video_s-c.reference_s)?a:b);if(Math.abs(selected.video_s-c.reference_s)>.251)throw Error('Missing checkpoint');const s=selected.status.surfaces[0];
 const result={id:name,reference_s:c.reference_s,prediction_s:selected.video_s,alert:s.candidates.some(x=>x.alert),quality:s.quality,baseline:s.baseline,valid:!!s.baseline&&!s.capturing&&s.quality===0,occupancy:s.occupancy,layout_changed:s.layout_changed,candidates:s.candidates,first_alert_s:seq.find(x=>x.status.surfaces[0].candidates.some(c=>c.alert))?.video_s??null,baseline_ready_s:seq.find(x=>x.status.surfaces[0].baseline)?.video_s??null,frames:seq.length,process_metrics:logs.match(/EVAL[^\r\n]*/)?.[0]};write(path.join(work,'result.json'),result);console.log(JSON.stringify(result));write(path.join(out,'progress.json'),{state:'resting',completed:i+1,total:51});if(i<jobs.length-1)await new Promise(r=>setTimeout(r,m.between_videos_ms));
 }write(path.join(out,'completed.json'),{finished_at:new Date().toISOString(),primary:50,supplemental:1});write(path.join(out,'progress.json'),{state:'completed',completed:51,total:51});}
async function main(){console.log('Output: '+out);if(process.argv[2]==='--prepare')prepare();else if(process.argv[2]==='--stills')stills();else if(process.argv[2]==='--run')await run();else throw Error('Use --prepare, --stills OUTPUT, --run OUTPUT');}
if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1;});
