const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function metrics(rows){const counts={TP:0,FP:0,TN:0,FN:0};for(const r of rows){if(typeof r.expected_alert!=='boolean'||typeof r.alert!=='boolean')throw Error('Unreviewed/non-boolean label');counts[r.expected_alert?(r.alert?'TP':'FN'):(r.alert?'FP':'TN')]++;}const {TP,FP,TN,FN}=counts,n=rows.length;return {n,...counts,precision:TP+FP?TP/(TP+FP):null,recall:TP+FN?TP/(TP+FN):null,f1:2*TP+FP+FN?2*TP/(2*TP+FP+FN):null,accuracy:n?(TP+TN)/n:null,quality_coverage:n?rows.filter(x=>x.valid).length/n:null};}
function summarize(dir){
 const read=p=>JSON.parse(fs.readFileSync(path.join(dir,p),'utf8')),m=read('manifest.json'),labels=read('labels.json');read('completed.json');
 if(m.cases.length!==50||new Set(m.cases.map(x=>x.id)).size!==50||labels.length!==50||new Set(labels.map(x=>x.id)).size!==50)throw Error('Expected 50 unique cases and labels');
 const rows=m.cases.map(c=>{const l=labels.find(x=>x.id===c.id),r=read(c.id+'/result.json');if(!l||r.id!==c.id||Math.abs(r.prediction_s-c.reference_s)>.251)throw Error('Case/label mismatch');return {...r,...l,session:c.session,video:c.video,outcome:l.expected_alert?(r.alert?'TP':'FN'):(r.alert?'FP':'TN')};});
 const supplement={...read('S36-fixture/result.json'),expected_alert:false};
 const groups={all50:metrics(rows),without_protocol_changed_S33:metrics(rows.filter(x=>x.id!=='S33')),older_session:metrics(rows.filter(x=>x.session.includes('2026-09-11'))),new_session:metrics(rows.filter(x=>x.session.includes('2026-09-14')))};
 const totals={frames:0,person_runs:0,object_runs:0,person_wall_s:0,object_wall_s:0};for(const r of rows)for(const key of Object.keys(totals))totals[key]+=Number(r.process_metrics?.match(new RegExp(key+'=([0-9.]+)'))?.[1]||0);
 const summary={scope:m.scope,groups,quality_invalid:rows.filter(x=>!x.valid).map(x=>x.id),false_positives:rows.filter(x=>x.outcome==='FP').map(x=>x.id),false_negatives:rows.filter(x=>x.outcome==='FN').map(x=>x.id),supplemental_S36:{initial:rows.find(x=>x.id==='S36'),registered:supplement},totals,labels_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,'labels.json'))).digest('hex'),cpu_measured:false,exact_latency_evaluated:false,full_event_accuracy_evaluated:false,independent_test:false};
 fs.writeFileSync(path.join(dir,'summary.json'),JSON.stringify(summary,null,2));fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify(rows,null,2));
 const csv=['id,session,expected_alert,alert,outcome,reference_s,prediction_s,quality,valid,first_alert_s'];for(const r of rows)csv.push([r.id,r.session,r.expected_alert,r.alert,r.outcome,r.reference_s,r.prediction_s,r.quality,r.valid,r.first_alert_s??''].join(','));fs.writeFileSync(path.join(dir,'results.csv'),csv.join('\n')+'\n');
 const pct=x=>x==null?'N/A':(100*x).toFixed(1)+'%';const md=['# 50개 원본 영상 초기 설정 평가 결과','','이 표는 관찰 후반 단일 체크포인트의 알림 정책 판정이다. 전체 사건 성능·독립 테스트 성능이 아니다.','','| 구분 | n | TP | FP | TN | FN | 정밀도 | 재현율 | F1 | 정확도 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|'];for(const [name,g]of Object.entries(groups))md.push(`| ${name} | ${g.n} | ${g.TP} | ${g.FP} | ${g.TN} | ${g.FN} | ${pct(g.precision)} | ${pct(g.recall)} | ${pct(g.f1)} | ${pct(g.accuracy)} |`);
 md.push('','## 영상별 결과','','| ID | 기대 알림 | 실제 알림 | 판정 | 영상 초 | 품질 | 비고 |','|---|---|---|---|---:|---:|---|');for(const r of rows)md.push(`| ${r.id} | ${r.expected_alert?'있음':'없음'} | ${r.alert?'있음':'없음'} | ${r.outcome} | ${r.prediction_s} | ${r.quality} | ${r.protocol_note||''} |`);
 md.push('','## S36 비치물 등록 별도 비교','',`초기 알림=${summary.supplemental_S36.initial.alert}, 등록 후 알림=${supplement.alert}. 초기 50개 합계에 추가 실행을 중복 산입하지 않는다.`,'','## 제한','','- 20개 기존 세션 + 30개 추가 세션을 함께 평가했다. 개발 자료와 검토 후 재촬영을 포함하므로 독립 테스트가 아니다.','- S33은 처음부터 컵이 있던 원본 그대로 실행했다. 제거 후 단일 시점의 무알림 여부만 평가하며 사전 알림 형성·해제 성능을 검증하지 않는다. S33 제외 합계도 함께 보고한다.','- S36/S37은 비치물 정책상 무알림이 기대되지만 초기 설정에는 비치물 등록이 없다. S36만 별도 등록 비교한다.','- S39는 컵이 있어도 사용 중이므로 기대 알림 없음이다. 단순 물체 존재 이진 분류와 구별한다.','- S35의 대체 물품, S38의 비치물 등록 여부, S46의 그림자 행동 등 원래 시나리오 충족 여부는 별도다. 시점 잔류/사용 상태만 정답으로 삼았다.','- 품질 무효는 깨끗함으로 판정한 것이 아니다. 알림 전달 점수의 분모에는 포함하고 품질 유효 비율을 병기한다.','- 2 Hz, 추적기 미사용, 카메라 품질 정상 가정, 동기식 AI 평가 어댑터. 정확한 퇴석/탐지 지연, 위치 mAP, CPU, 효율 ON/OFF는 측정하지 않았다.','- 영상·운영 설정을 수정하지 않았다. 모델·실행 파일은 초기 스냅샷을 사용했다.','');fs.writeFileSync(path.join(dir,'report.md'),md.join('\n'));return summary;
}
module.exports={metrics,summarize};if(require.main===module)try{console.log(JSON.stringify(summarize(path.resolve(process.argv[2])),null,2));}catch(e){console.error(e);process.exitCode=1;}
